[target.wasm32-unknown-unknown]
runner = "wasm-server-runner"
# It's recommended to set the flag on a per-target basis:
rustflags = ['--cfg', 'getrandom_backend="wasm_js"']
[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"